name: Ilan Kontrol

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Paketleri kur
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 google-auth

      # ğŸ”¥ FIREBASE SERVICE ACCOUNT DOSYASI
      - name: Firebase key yaz
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_B64 }}" | tr -d '\r' | base64 --decode > service-account.json

      - name: Scripti Ã§alÄ±ÅŸtÄ±r
        run: python checker.py
